services:
    gateway_service:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: gateway_service
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - ceo_network
        depends_on:
            - gateway_mysql

    gateway_web:
        image: nginx:alpine
        container_name: gateway_web
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - gateway_service
        networks:
            - ceo_network

    gateway_mysql:
        image: mysql:8.0
        container_name: gateway_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: gateway_service
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql-init:/docker-entrypoint-initdb.d
        ports:
            - "3307:3306"
        networks:
            - ceo_network

networks:
    ceo_network:
        external: true

volumes:
    mysql_data:
